version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: lumina-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # 本地开发关闭密码验证，防止 Spring Boot 连不上
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" # 限制内存，防止 Docker 把你电脑卡死
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7.0-alpine
    container_name: lumina-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  es_data:
  redis_data: